import { NextResponse } from "next/server";
import { getRecentNotifications } from "@/lib/data/notifications-repository";
import type { ApiResponse } from "@/types/api";
import type { DashboardData } from "@/types/dashboard";

const dashboardData: DashboardData = {
  kpis: [
    {
      id: "total-calls",
      label: "Total Calls",
      value: "12,847",
      change: 12.4,
      changeLabel: "vs last month",
      trend: "up",
      icon: "phone",
      accent: "blue",
    },
    {
      id: "success-rate",
      label: "Success Rate",
      value: "78.6%",
      change: 3.2,
      changeLabel: "vs last month",
      trend: "up",
      icon: "check-circle",
      accent: "emerald",
    },
    {
      id: "avg-call-duration",
      label: "Avg Duration",
      value: "4m 32s",
      change: 0,
      changeLabel: "vs last month",
      trend: "neutral",
      icon: "clock",
      accent: "slate",
    },
    {
      id: "answered-calls",
      label: "Answered Calls",
      value: "9,412",
      change: 7.8,
      changeLabel: "vs last month",
      trend: "up",
      icon: "phone-incoming",
      accent: "cyan",
    },
    {
      id: "missed-calls",
      label: "Missed Calls",
      value: "1,086",
      change: -2.4,
      changeLabel: "vs last month",
      trend: "down",
      icon: "phone-missed",
      accent: "rose",
    },
    {
      id: "active-agents-voice",
      label: "Active Agents",
      value: "18",
      change: 4.2,
      changeLabel: "vs last month",
      trend: "up",
      icon: "bot",
      accent: "violet",
    },
    {
      id: "survey-completed",
      label: "Total Completed Survey",
      value: "1,248",
      change: 9.4,
      changeLabel: "vs last month",
      trend: "up",
      icon: "check-circle",
      accent: "emerald",
    },
    {
      id: "survey-created",
      label: "Total Created Survey",
      value: "186",
      change: 6.1,
      changeLabel: "vs last month",
      trend: "up",
      icon: "file-plus",
      accent: "violet",
    },
    {
      id: "captured-data",
      label: "Captured Data",
      value: "3,291",
      change: 8.1,
      changeLabel: "vs last month",
      trend: "up",
      icon: "database",
      accent: "cyan",
    },
    {
      id: "survey-pending",
      label: "Pending Survey",
      value: "64",
      change: -3.5,
      changeLabel: "vs last month",
      trend: "down",
      icon: "clock",
      accent: "amber",
    },
    {
      id: "survey-ongoing",
      label: "Ongoing Survey",
      value: "28",
      change: 4.8,
      changeLabel: "vs last month",
      trend: "up",
      icon: "loader",
      accent: "rose",
    },
    {
      id: "survey-responses",
      label: "Survey Responses",
      value: "1,956",
      change: 15.7,
      changeLabel: "vs last month",
      trend: "up",
      icon: "clipboard",
      accent: "indigo",
    },
  ],
  callSuccessTrend: [
    { label: "Mon", value: 72, success: 72, failed: 28 },
    { label: "Tue", value: 75, success: 75, failed: 25 },
    { label: "Wed", value: 68, success: 68, failed: 32 },
    { label: "Thu", value: 81, success: 81, failed: 19 },
    { label: "Fri", value: 79, success: 79, failed: 21 },
    { label: "Sat", value: 65, success: 65, failed: 35 },
    { label: "Sun", value: 58, success: 58, failed: 42 },
  ],
  dailyCalls: [
    { label: "6 AM", value: 42, calls: 42 },
    { label: "8 AM", value: 128, calls: 128 },
    { label: "10 AM", value: 245, calls: 245 },
    { label: "12 PM", value: 198, calls: 198 },
    { label: "2 PM", value: 312, calls: 312 },
    { label: "4 PM", value: 276, calls: 276 },
    { label: "6 PM", value: 154, calls: 154 },
    { label: "8 PM", value: 68, calls: 68 },
  ],
  callOutcomes: [
    { name: "Completed", value: 8420, fill: "var(--brand)" },
    { name: "No Answer", value: 2140, fill: "var(--brand-blue)" },
    { name: "Busy", value: 1280, fill: "var(--chart-2)" },
    { name: "Failed", value: 1007, fill: "var(--chart-4)" },
  ],
  recentActivities: [
    {
      id: "act-1",
      type: "call",
      title: "Outbound call completed",
      description: "Successfully reached John Mitchell for Q2 survey.",
      performedBy: "Sarah Chen",
      occurredAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    },
    {
      id: "act-2",
      type: "deal_update",
      title: "Survey status updated",
      description: "Enterprise NPS Survey moved to active status.",
      performedBy: "Alex Rivera",
      occurredAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    },
    {
      id: "act-3",
      type: "email",
      title: "Survey invitation sent",
      description: "Bulk email sent to 240 customers in Segment B.",
      performedBy: "System",
      occurredAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    },
    {
      id: "act-4",
      type: "note",
      title: "Customer note added",
      description: "Follow-up scheduled for Acme Corp renewal discussion.",
      performedBy: "Mike Johnson",
      occurredAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
    {
      id: "act-5",
      type: "status_change",
      title: "Response flagged for review",
      description: "Negative feedback flagged in Healthcare CX survey.",
      performedBy: "System",
      occurredAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    },
  ],
  recentNotifications: [],
  recentCustomers: [
    {
      id: "cust-1",
      name: "John Mitchell",
      email: "john.mitchell@acmecorp.com",
      company: "Acme Corp",
      status: "active",
      lastContactAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
      id: "cust-2",
      name: "Emily Watson",
      email: "emily@techflow.io",
      company: "TechFlow",
      status: "active",
      lastContactAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    },
    {
      id: "cust-3",
      name: "Raj Patel",
      email: "raj.patel@globalfin.com",
      company: "GlobalFin",
      status: "lead",
      lastContactAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
    {
      id: "cust-4",
      name: "Lisa Thompson",
      email: "lisa.t@healthplus.org",
      company: "HealthPlus",
      status: "active",
      lastContactAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    },
    {
      id: "cust-5",
      name: "David Kim",
      email: "david.kim@retailmax.com",
      company: "RetailMax",
      status: "inactive",
      lastContactAt: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    },
  ],
};

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 600));

  const recentNotifications = getRecentNotifications(4).map((n) => ({
    id: n.id,
    title: n.title,
    description: n.description,
    type: n.type,
    read: n.read,
    createdAt: n.createdAt,
  }));

  const response: ApiResponse<DashboardData> = {
    success: true,
    data: { ...dashboardData, recentNotifications },
  };

  return NextResponse.json(response);
}
